== Description

[.text-justify]
CH32V103 series series MCU incorporate a 32-bit _RISC-V_ RISC-V3A core based on the `RV32IMAC` open-standard ISA, high-speed embedded memories (up to 64kB of FLASH memory and up to 20kB of SRAM) with instruction pre-fetch and a wide range of I/O and peripherals. All series parts feature a 12-bit ADC with TouchKey, one advanced 16-bit timer capable of motor control applications plus a minimum of two 16-bit general purpose timers, as well as a range of communication interfaces including SPI, I&sup2;C, 2 &times; USART and USBHD 2.0FS host and device functionality.

[.text-justify]
The devices operate at a supply range of 2.7 to 5.5V, with a maximum core frequency of 80MHz. Core components and peripherals are interconnected via two APBs and one AHB, and clock supplies can be disabled and core power saving modes can be used for low-power applications. RTC and backup registers can be powered independently through a battery supply input. All series devices are capable of operating across the industrial grade temperature range between -40 and +85&deg;C, and are available in package sizes QFN48, LQFP48 and LQFP64.

[.text-justify]
CH32V103 series devices are suitable for use in motor control applications, handheld equipment, PC peripheral devices and gaming peripherals, GPS platforms, PLCs, inverters, printers and scanners, video intercom systems and HVAC equipment.

=== Device overview

[.text-justify]
CH32V103 series devices are offered in three package variants spanning a set of four device models, each with a specific package, memory and peripherals configuration. All available configurations are shown in <<model-comparison>>. The device internal block structure is shown in <<system-diagram>>.

[#model-comparison]
.Model Comparison
include::{tablesdir}/model-comparison.adoc[]

[#system-diagram]
.System Block Diagram
image::CH32V103_System_Diagram.svg[align=center]