name: Deploy GitHub Pages

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    name: Build HTML pages
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Prepare build container
      uses: tonynv/asciidoctor-action@master

    - name: Build landing page
      run: "asciidoctor -b html5 outputs index.adoc"

    - name: Build datasheet
      run: "asciidoctor -b html5 -r asciidoctor-diagram -r asciidoctor-kroki -D outputs/datasheet datasheet/index.adoc"

    - name: Copy resources
      run: "mkdir -p outputs/resources/img && cp resources/img/*.svg outputs/resources/img/"

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./outputs