name: Deploy GitHub Pages

on:
  push:
    branches:
    - master
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-18.04
    name: Build HTML pages
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Prepare version information file
      run: |
        echo ":release-type: `if [ "${{ github.ref_type }}" == "tag" ]; then echo "release"; else echo "preview"; fi`" > version.adoc
        echo ":ref-name: ${{ github.ref_name }}" >> version.adoc
        echo ":commit-sha: `echo ${{ github.sha }} | cut -c1-7`" >> version.adoc

    - name: Build landing page
      uses: tonynv/asciidoctor-action@master
      with:
        program: "asciidoctor -b html5 -D outputs index.adoc"

    - name: Build HTML datasheet
      uses: tonynv/asciidoctor-action@master
      with:
        program: "asciidoctor -b html5 -r asciidoctor-diagram -r asciidoctor-kroki -D outputs/datasheet datasheet/index.adoc"

    - name: Prepare PDF build
      run: |
        find */* -type f -name "*.adoc" -exec sed -i 's/&commat;/@/g; s/&deg;/°/g; s/&lowbar;/_/g; s/&sup2;/²/g; s/&times;/×/g' {} +
        find */* -type f -name "*.adoc" -exec sed -i 's/.svg/.png/g;' {} +
        
    - name: Build PDF datasheet
      uses: tonynv/asciidoctor-action@master
      with:
        program: "asciidoctor-pdf -a build-type=pdf -r asciidoctor-diagram -r asciidoctor-kroki -D outputs/ -o ch32v103_ds.pdf datasheet/index.adoc"

    - name: Copy resources
      run: "sudo mkdir -p outputs/resources/img && sudo cp resources/img/*.svg outputs/resources/img/"

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./outputs